---
kind: pipeline
type: kubernetes
name: default

trigger:
  branch:
  - main

steps:
- name: publish
  image: plugins/kaniko-ecr
  settings:
    create_repository: true    
    repo: devops/${DRONE_REPO_NAME}
    tags:
    - git-${DRONE_COMMIT_SHA:0:7}
    - latest
    registry:
      from_secret: ecr_registry
    access_key:
      from_secret: ecr_access_key
    secret_key:
      from_secret: ecr_secret_key
  when:
    event:
    - push
